//! Every released version of the *event* format, as committed bytes, with the
//! promise this project makes about them: a current build replays all of them
//! to the same world.
//!
//! The frame format has had this since v0.5 (`format_compatibility.rs`); the
//! event format had nothing, which mattered the moment it grew its first
//! extension record.
//!
//! - `compat_events_v1.stev` predates `ResetDictionaries`, so it is what a
//!   capture from v0.4 and earlier looks like.
//! - `compat_events_v2.stev` is the same playthrough with the reset record,
//!   which is what most existing capture folders hold.
//! - `compat_events_v3.stev` is the same again with a `RemoveName` extension,
//!   which is what this build writes.
//!
//! All three describe one sequence of play, so this is three encodings of one
//! thing rather than three files that each happen to parse. Regenerated by the
//! ignored `regenerate_event_fixtures` test, and not to be regenerated merely
//! to make this file pass: a failure here means somebody's capture stopped
//! replaying.

use std::path::PathBuf;

use save_timelapse::event::{stream_log, Event, LoggedEvent};
use save_timelapse::wire::ByteWriter;

fn fixture_path(name: &str) -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "events", name].iter().collect()
}

fn replay(name: &str) -> (Vec<LoggedEvent>, usize) {
    let path = fixture_path(name);
    let mut stream = stream_log(&path).unwrap_or_else(|e| panic!("{name} must still open: {e}"));
    let events: Vec<LoggedEvent> = (&mut stream).collect();
    (events, stream.unknown_extensions())
}

/// The sequence all three fixtures describe: build a drill on an ore tile,
/// rotate it, mine the ore out from under it, then mine the drill.
fn expected() -> Vec<(u64, &'static str, Event)> {
    let add = |d: u8| Event::AddEntity { name: "electric-mining-drill".to_string(), x: 1.5, y: 2.5, d, w: 3, h: 3, id: Some(42) };
    vec![
        (100, "nauvis", add(0)),
        (140, "nauvis", add(4)),
        // Only version 3 can say this removal was for the ore. The older two
        // carry the same removal with nothing to distinguish it, which is the
        // bug the record closes and is preserved here on purpose.
        (180, "nauvis", Event::RemoveEntity { id: None, pos: (1.5, 2.5), name: None }),
        (220, "nauvis", Event::RemoveEntity { id: Some(42), pos: (1.5, 2.5), name: None }),
    ]
}

fn as_expected(events: &[LoggedEvent]) -> Vec<(u64, &str, Event)> {
    events.iter().map(|e| (e.tick, e.surface.as_str(), e.event.clone())).collect()
}

/// A capture from any release this project has made still replays, and replays
/// to the same events. Version 3 additionally knows which of two things at one
/// position a removal was for; everything else must be identical.
#[test]
fn every_released_event_version_replays_and_agrees() {
    for name in ["compat_events_v1.stev", "compat_events_v2.stev"] {
        let (events, unknown) = replay(name);
        assert_eq!(as_expected(&events), expected(), "{name} replays differently");
        assert_eq!(unknown, 0, "{name} predates extension records entirely");
    }

    let (events, unknown) = replay("compat_events_v3.stev");
    assert_eq!(unknown, 0, "the removal name is a record this build understands");

    let mut want = expected();
    want[2].2 = Event::RemoveEntity { id: None, pos: (1.5, 2.5), name: Some("iron-ore".to_string()) };
    assert_eq!(as_expected(&events), want, "version 3 names the deposit that removal was for");
}

/// The extension contract, checked rather than assumed: a tool that does not
/// know `RemoveName` must skip it by its own declared length and carry on. The
/// same bytes with only the tag changed stand in for that tool, since the
/// reader treats any unrecognised tag at or above 128 identically.
#[test]
fn a_tool_that_does_not_know_the_removal_name_still_replays_everything_else() {
    let bytes = std::fs::read(fixture_path("compat_events_v3.stev")).unwrap();
    let unknown_tag = bytes.iter().position(|&b| b == 128).expect("the fixture carries a RemoveName record");
    let mut older = bytes.clone();
    older[unknown_tag] = 200;

    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("events_100.stev");
    std::fs::write(&path, &older).unwrap();

    let mut stream = stream_log(&path).unwrap();
    let events: Vec<LoggedEvent> = (&mut stream).collect();

    assert_eq!(as_expected(&events), expected(), "every core record must survive an unreadable extension");
    assert_eq!(stream.unknown_extensions(), 1, "and the tool must be able to say it is behind the mod");
}

/// Writes the three fixtures. Ignored: they are committed bytes standing for
/// what released builds wrote, so regenerating them is a deliberate act, not
/// something to do because this file went red.
///
/// Written here with a raw byte writer rather than through any production
/// code, so a reader bug cannot hide behind a writer that shares it. The Lua
/// side's own byte layout is pinned separately by `mod/tests/encode_test.lua`;
/// the two together are what make this meaningful.
#[test]
#[ignore]
fn regenerate_event_fixtures() {
    let dir: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "events"].iter().collect();
    std::fs::create_dir_all(&dir).unwrap();

    for (version, name) in [(1u8, "compat_events_v1.stev"), (2, "compat_events_v2.stev"), (3, "compat_events_v3.stev")] {
        let mut w = ByteWriter::new();
        w.magic(b"STE1").u8(version);

        w.u8(2).u64(100); // SetTick
        w.u8(1).string("nauvis"); // DefineSurface 0
        w.u8(0).string("electric-mining-drill"); // DefineName 0
        w.u8(3).u16(0).i32(15).i32(25).u8(0).u8(3).u8(3).u64(42).u16(0); // AddEntity

        // A save reload lands here: version 2 and later say so, version 1
        // cannot and silently mislabels everything after it. The fixtures
        // sidestep that by redefining the same names in the same order, so all
        // three still describe one sequence.
        w.u8(2).u64(140);
        if version >= 2 {
            w.u8(7); // ResetDictionaries
            w.u8(1).string("nauvis");
            w.u8(0).string("electric-mining-drill");
        }
        w.u8(3).u16(0).i32(15).i32(25).u8(4).u8(3).u8(3).u64(42).u16(0); // rotated

        w.u8(2).u64(180);
        if version >= 3 {
            w.u8(0).string("iron-ore"); // DefineName 1
            let mut inner = ByteWriter::new();
            inner.varint(1);
            let payload = inner.into_vec();
            w.u8(128).varint(payload.len() as u64);
            for byte in payload {
                w.u8(byte);
            }
        }
        w.u8(4).i32(15).i32(25).u64(0).u16(0); // RemoveEntity: the ore

        w.u8(2).u64(220);
        w.u8(4).i32(15).i32(25).u64(42).u16(0); // RemoveEntity: the drill

        std::fs::write(dir.join(name), w.into_vec()).unwrap();
        println!("wrote {name}");
    }
}
