//! Every released version of the frame format, as committed bytes, with the
//! promise this project makes about them: a current build opens all of them.
//!
//! An integration test rather than a unit test in `frame.rs`, so it reaches the
//! format the way a user's capture does and depends on no test-only helper.
//!
//! - `frame_0001.stfr` is a real version 1 capture, as the mod shipped it
//!   through v0.3.
//! - `compat_v2.stfr` is that same frame in version 2, what sits in most
//!   existing capture folders.
//! - `compat_v3.stfr` is that same frame in version 3, what this build writes.
//!
//! All three hold one frame's real captured contents, so this is three
//! encodings of one thing rather than three files that each happen to parse.
//! Regenerated by the ignored `regenerate_compatibility_fixtures` test, and not
//! to be regenerated merely to make this file pass.

use std::path::PathBuf;

use save_timelapse::frame::{self, Entity, Frame, Tile};

fn fixture(name: &str) -> Frame {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "frames", name].iter().collect();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    frame::read_binary(&bytes).unwrap_or_else(|e| panic!("{name} must still load: {e}"))
}

/// Entities are compared as a sorted multiset because version 2 groups them
/// by name on the way out, so the array order legitimately differs between
/// encodings. What has to survive is every entity, intact, not its index.
fn entity_keys(entities: &[Entity]) -> Vec<(String, i32, i32, u8, u32, u32)> {
    let mut keys: Vec<_> = entities
        .iter()
        .map(|e| ((*e.n).to_string(), (e.x * 10.0).round() as i32, (e.y * 10.0).round() as i32, e.d, e.w, e.h))
        .collect();
    keys.sort();
    keys
}

fn tile_keys(tiles: &[Tile]) -> Vec<(String, i32, i32)> {
    let mut keys: Vec<_> = tiles.iter().map(|t| ((*t.n).to_string(), t.x, t.y)).collect();
    keys.sort();
    keys
}

/// A capture from any release this project has made still opens, and opens to
/// the same frame. A failure here is not a test to adjust: it means somebody's
/// older capture no longer loads.
#[test]
fn every_released_frame_version_loads_and_agrees() {
    let versions = [("v1 (through v0.3)", "frame_0001.stfr"), ("v2 (v0.4)", "compat_v2.stfr"), ("v3 (v0.5)", "compat_v3.stfr")];

    let frames: Vec<(&str, Frame)> = versions.iter().map(|(label, name)| (*label, fixture(name))).collect();

    let (first_label, first) = &frames[0];
    assert!(!first.entities.is_empty(), "the fixture is meant to carry real captured data");

    for (label, frame) in &frames[1..] {
        assert_eq!(frame.tick, first.tick, "{label} disagrees with {first_label} on tick");
        assert_eq!(frame.surface, first.surface, "{label} disagrees with {first_label} on surface");
        assert_eq!(frame.count, first.count, "{label} disagrees with {first_label} on entity count");
        assert_eq!(
            entity_keys(&frame.entities),
            entity_keys(&first.entities),
            "{label} disagrees with {first_label} on entities"
        );
        assert_eq!(tile_keys(&frame.tiles), tile_keys(&first.tiles), "{label} disagrees with {first_label} on tiles");
    }
}

/// The version byte is what the whole compatibility story rests on, so the
/// fixtures really being the versions they claim is worth pinning: otherwise
/// all three could become the same version and the test above would still
/// pass.
#[test]
fn the_fixtures_carry_the_version_bytes_they_claim() {
    for (name, expected) in [("frame_0001.stfr", 1u8), ("compat_v2.stfr", 2), ("compat_v3.stfr", 3)] {
        let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "frames", name].iter().collect();
        let bytes = std::fs::read(&path).unwrap();
        assert_eq!(&bytes[..4], b"STF1", "{name}: magic");
        assert_eq!(bytes[4], expected, "{name}: version byte");
    }
}

/// A version above what this build knows is refused with a message that says
/// so, rather than guessed at.
///
/// The deliberate limit of the extension contract: additive changes ride in
/// extension records and stay readable, where a core layout change would not.
/// Nothing after version 3 is expected to trip this.
#[test]
fn a_capture_from_a_future_core_version_is_refused_clearly() {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "frames", "compat_v3.stfr"].iter().collect();
    let mut bytes = std::fs::read(&path).unwrap();
    bytes[4] = 99;

    let err = frame::read_binary(&bytes).expect_err("a version this build cannot know must not parse");
    let message = err.to_string();
    assert!(message.contains("version"), "the error must name the problem, got: {message}");
}
